# **Numpy Basics**

In [16]:
# import Numpy library and create an array
import numpy as np
# 0D Array
n = np.array(42)
n

array(42)

In [17]:
# 1D Array
arr = np.array([1,2,3,4,5])

arr

array([1, 2, 3, 4, 5])

In [18]:
# 2D Array
twod_arr = np.array([[1,2,3],[4,5,6]])
twod_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
# 3D Array
threed_arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
threed_arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [20]:
# Printing dimensions of the previously created arrays

print(n.ndim)
print(arr.ndim)
print(twod_arr.ndim)
print(threed_arr.ndim)

0
1
2
3


In [21]:
# Creating higher dimensional arrays
multi_arr = np.array([1,2,3,4,5], ndmin=5)

print(multi_arr)

print(multi_arr.ndim)


[[[[[1 2 3 4 5]]]]]
5


# **Accessing Array Elements**

In [22]:
# Accessing first element of the array

arr = np.array([1,2,3,4,5])
print(arr[0])

1


In [23]:
# Accessing 3rd element of the array

print(arr[2])

3


In [25]:
# Accessing an element of 2D array

arr = np.array([[1,2,3],[4,5,6]])
print(arr[0,1])
print(arr[1,1])

2
5


In [26]:
# Accessing an element of 3D array

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


In [27]:
# Accessing element of an array through negative index

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,-1])

10
